runtime: nodejs
env: flex

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "your-database-url"
  API_KEY: "your-api-key"
  MONGODB_URI: "mongodb+srv://achikoogorgadze:bMnGFV01LBy14rra@cluster0.ot8hfjx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
GOOGLE_CLIENT_ID: "12587126397-72erlistvpbaakungbu03vjrc5lebm5c.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "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"

COOKIE_KEY: "jrtvGs82dYVKS9d8lzvhNgo8dZtwJadA"
SESSION_SECRET: "jrtvGs82dYVKS9d8lzvhNgo8dZtwJadA"
GCLOUD_BUCKET: "drive-app"
GOOGLE_REDIRECT_URI: "http://localhost:3000/dashboard"
